[package]
name = "aoc_2019"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.11"
criterion = "0.5.1"
flamegraph = "0.6.7"
itertools = "0.14.0"

[[bench]]
name = "all_days"
harness = false
