#include "prelude.hpp"
tuple<int, int> day_01(const string& input);
tuple<int, int> day_02(const string& input);
tuple<int, int> day_03(const string& input);
tuple<int, int> day_04(const string& input);
tuple<long, long> day_05(const string& input);
tuple<int, int> day_06(const string& input);
tuple<int, int> day_07(const string& input);
tuple<int, int> day_08(const string& input);
tuple<int, int> day_09(const string& input);
tuple<int, int> day_10(const string& input);
tuple<string, string> day_11(string input);
tuple<int, int> day_12(const string& input);
tuple<int, int> day_13(const string& input);
tuple<int, int> day_14(const string& input);
tuple<int, int> day_15(const string& input);
tuple<int, int> day_16(const string& input);
tuple<int, int> day_17(const string& input);
tuple<int, int> day_18(const string& input);
tuple<int, int> day_19(const string& input);
tuple<int, int> day_20(const string& input);
tuple<int, int> day_21(const string& input);
tuple<int, int> day_22(const string& input);
tuple<int, int> day_23(const string& input);
tuple<long, long> day_24(const string& input);
tuple<long, long> day_25(const string& input);