name:                aoc-haskell
version:             0.1.0.0
github:              "ajmorton/aoc-haskell"
license:             BSD3
author:              "Andrew Morton"
maintainer:          "ajmorton2@gmail.com"
copyright:           "2021 Andrew Morton"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Advent of code 2016 - Haskell
# category:            Web

description:         Solutions for Advent of Code 2016 in Haskell

dependencies:
- base >= 4.7 && < 5
- text
- split == 0.2.3.5
- containers
- sort == 1.0.0.0
- MissingH == 1.5.0.1
- parallel == 3.2.2.0
- cryptonite == 0.30
- bytestring

library:
  source-dirs: src

executables:
  aoc-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc-haskell

tests:
  aoc-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc-haskell
