cc_library(
    name = "solutions",
    hdrs = ["prelude.hpp", "days.hpp" ],
    srcs = ["prelude.cpp", "day_01.cpp", "day_02.cpp", "day_03.cpp", "day_04.cpp", "day_05.cpp",
                           "day_06.cpp", "day_07.cpp", "day_08.cpp", "day_09.cpp", "day_10.cpp",
                           "day_11.cpp", "day_12.cpp", "day_13.cpp", "day_14.cpp", "day_15.cpp",
                           "day_16.cpp", "day_17.cpp", "day_18.cpp", "day_19.cpp", "day_20.cpp",
                           "day_21.cpp", "day_22.cpp", "day_23.cpp", "day_24.cpp", "day_25.cpp"],
    visibility = ["//:__pkg__", "//test:__pkg__"],
    deps = ["@boost//:conversion", "@boost//:algorithm", "@boost//:uuid"],
)