cc_library(
    name = "solutions",
    hdrs = ["prelude.hpp", "day_01.hpp", "day_02.hpp", "day_03.hpp"],
    srcs = ["prelude.cpp", "day_01.cpp", "day_02.cpp", "day_03.cpp"],
    visibility = ["//:__pkg__", "//test:__pkg__"]
)