workspace(name = "advent_of_code_2015")

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "catch2",
    tag = "v2.13.6",
    remote = "https://github.com/catchorg/Catch2",
)

git_repository(
    name = "com_github_nelhage_rules_boost",
    commit = "8443ad6f1c806823f03162a6e199275ef052b35e",
    shallow_since = "1625099911 -0700",
    remote = "https://github.com/nelhage/rules_boost",
)

load("@com_github_nelhage_rules_boost//:boost/boost.bzl", "boost_deps")
boost_deps()